Le_Domain='bdyear.sn-server.store'
Le_Alt='no'
Le_Webroot='no'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme-v02.api.letsencrypt.org/directory'
Le_HTTPPort='80'
Le_Keylength='ec-256'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/3596100301/540393997191'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/3596100301/540393997191'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/05c609df0445304e2dc814f84b18a0ef2de9'
Le_CertCreateTime='1785785432'
Le_CertCreateTimeStr='2026-08-03T19:30:32Z'
Le_NextRenewTimeStr='2026-10-03T12:55:34Z'
Le_NextRenewTime='1791032134'
Le_RealCertPath=''
Le_RealCACertPath=''
Le_RealKeyPath='/root/cert/bdyear.sn-server.store/privkey.pem'
Le_ReloadCmd='__ACME_BASE64__START_c3lzdGVtY3RsIHJlc3RhcnQgeC11aSAyPi9kZXYvbnVsbCB8fCByYy1zZXJ2aWNlIHgtdWkgcmVzdGFydCAyPi9kZXYvbnVsbA==__ACME_BASE64__END_'
Le_RealFullChainPath='/root/cert/bdyear.sn-server.store/fullchain.pem'
Le_InstallCertSuccessTime='1785788954'
Le_InstallCertSuccessTimeStr='2026-08-03T20:29:14Z'
