

#LOG_FILE="/root/.acme.sh/acme.sh.log"
#LOG_LEVEL=1

AUTO_UPGRADE='1'

#NO_TIMESTAMP=1

    
UPGRADE_HASH='261653ebf420a121b7594c0636b510bd6025fcb0'
DEFAULT_ACME_SERVER='https://acme-v02.api.letsencrypt.org/directory'
USER_PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
